// var n = "Rohini";
// var n = " Neha"

// document.write(n + "<br>");

// let fruit = "Apple";
//     fruit = "Mango";

// document.write(fruit+ "<br>");

// const state = "West Bengal";
//       state4 = "Bihar";

// document.write(state + "<br>")

// const state1 = "West Bengal";
// const state2 = "Bihar";

// document.write(state + state2)

// const fruit = {
//     Name: 'Apple'
// }
// document.write(Object.values(fruit))

// let x = 10;

// if(x < 100){
//     document.write("Number is lessthan 100");
// }

// write a programme in java script to take a any person is then check age is gretter than or equal to 18 then print he is 
// elegible to vote. and age is lessthan 18 , he is not eligible to vote.

// write a progmme to java script to take a number then check a number is equal to 70 then print
// he or she is old categary.and number is not equal to 70 then print he or she is youest qategory.


// let x = 18;

// if(x => 18 ){

//     document.write("Eligible for vote <br> ")
// }

   

// if(x < 18 ){

//     document.write("not eligible for vote ")
// }

// let a = 65;

// if(a == 70 ){

//     document.write("Older category <br>")
//  }
// if(a != 70 ){

//     document.write("Younger category ")
// }

// var n = 6;
//  if(n == 5){
//     document.write("Number is Equal to 5 = " +n)
//  }
//  else(
//     document.write("Number is not Equal to 5 = " +n)
//  )

// forloop

// for (n=1; n<=20; n++){
   
//    document.write(n+ '<br>')
// }

// var n=17;

// for(i=1; i<=10; i++){

// document.write(n+ "*" +i+ "=" +n*i+ '<br>');
// }

// While loop?

// let i=5;

// while(i<=10){

//     document.write(i+ "<br>")
//        i++;
// }

// do while loop?

// let i = 1;

// do{
//     document.write(i+ "<br>")
//     i++;
// }
// while(i <=20);

// increasing * pattern?

// let n=5;

// for(i=1; i<=5; i++){
//      let str= "*";

//     document.write(str.repeat(i) +'<br>');

// }

// switch?

// let month = 11;

// switch(month){
//     case 0: document.write("January");
//     break;
//     case 1: document.write("February");
//     break;
//     case 2: document.write("March");
//     break;
//     case 3: document.write("April");
//     break;
//     case 4: document.write("May");
//     break;
//     case 5: document.write("June");
//     break;
//     case 6: document.write("July");
//     break;
//     case 7: document.write("August");
//     break;
//     case 8: document.write("September");
//     break; 
//     case 9: document.write("October");
//     break;
//     case 10: document.write("November");
//     break;
//     case 11: document.write("December");
//     break;
//     default: document.write("Month is not matching")
// }

// Array1?

// let stu = ["Student1<br>","Student2", "Student3", "Student4<br>","Student5","Student6","Student7","Student8","Student9","Student10"];

// document.write(stu);

// Array2?

// let f = new Array();

// f[0]="mango";
// f[1]="apple";
// f[2]="orange";

// document.write(f);

// document.write(f[1]);

// array3?

// let state = new Array("wb", "up", "bihar");

// document.write(state);

// function che(){
//     var n=document.getElementById('main');
//     n.style.backgroundColor = 'black';
//     n.style.borderRadius = '10px';
// }


// function img(){
//     alert("hello");
// }

// onmouseout

//  function text{
//     var m = document.getElementById('main');

//     m.style.backgroundColor = 'skyblue';
//     m.style.color = 'white';
//  }

// onchange

// function cheng(){
//    var m =document.getElementById('main');
//    m.style.backgroundColor = 'skyblue';
//    m.style.color = 'white';
// }

// onsubmit

// function sub(){
//  alert("sibmitted successfully")
// }

// length

// var lth = "hello hello"

// document.write(lth);

// document.getElementById('text').innerHTML=lth.length;

// var frst = "Aniruddhya" ;
// var sec = " Das ";
// var thd = "is a good boy";

// var sum = frst.concat(sec, thd);

// document.write(sum);

// upper case/ lowercase
 
// var text1 = "hello world hello world";

// document.write(text1.toUpperCase() + '<br>');


// var small = "welcome to all";

// document.write(small.toLowerCase());


// replace

// let language = "Javascript is scripting language";

// let allsea = language.replace("Javascript" , "PHP");

// document.write(allsea);

// let all = "PHP is scripting language";
//  let slaal = all.slice(15);

//  document.write(slaal);

let sua = "hello all";

let both = sua.substr(2, 5);

document.write(both);








